# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'hub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thub.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x01\n\x0c\x44\x65viceStatus\x12\x19\n\x11tenant_identifier\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65vice_identifier\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xd6\x01\n\x13NumericScalarValues\x12\x19\n\x11tenant_identifier\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65vice_identifier\x18\x02 \x01(\t\x12\x19\n\x11metric_identifier\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x01\x12\x0c\n\x04unit\x18\x06 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x07 \x01(\t\x12-\n\ttimestamp\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"4\n\x08Response\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x0f\n\x07message\x18\x02 \x01(\t*.\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07PENDING\x10\x02\x32\x8f\x01\n\x03Hub\x12K\n\x17SendNumericScalarValues\x12\x14.NumericScalarValues\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12;\n\x10SendDeviceStatus\x12\r.DeviceStatus\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=480
  _globals['_STATUS']._serialized_end=526
  _globals['_DEVICESTATUS']._serialized_start=76
  _globals['_DEVICESTATUS']._serialized_end=207
  _globals['_NUMERICSCALARVALUES']._serialized_start=210
  _globals['_NUMERICSCALARVALUES']._serialized_end=424
  _globals['_RESPONSE']._serialized_start=426
  _globals['_RESPONSE']._serialized_end=478
  _globals['_HUB']._serialized_start=529
  _globals['_HUB']._serialized_end=672
# @@protoc_insertion_point(module_scope)
